export const BondingCurveRegistryAbi = [
  {
    inputs: [{ internalType: 'address', name: '_admin', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'BondingCurveRegistry_CurveAlreadyExists',
    type: 'error',
  },
  {
    inputs: [],
    name: 'BondingCurveRegistry_CurveNameNotUnique',
    type: 'error',
  },
  { inputs: [], name: 'BondingCurveRegistry_OnlyOwner', type: 'error' },
  { inputs: [], name: 'BondingCurveRegistry_RequiresOwner', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'curveId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'curveAddress',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'string',
        name: 'curveName',
        type: 'string',
      },
    ],
    name: 'BondingCurveAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'oldAdmin',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newAdmin',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: 'bondingCurve', type: 'address' },
    ],
    name: 'addBondingCurve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'admin',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'convertToAssets',
    outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'convertToShares',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'count',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'currentPrice',
    outputs: [{ internalType: 'uint256', name: 'sharePrice', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'curveAddresses',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'curveIds',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'getCurveMaxAssets',
    outputs: [{ internalType: 'uint256', name: 'maxAssets', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'getCurveMaxShares',
    outputs: [{ internalType: 'uint256', name: 'maxShares', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'getCurveName',
    outputs: [{ internalType: 'string', name: 'name', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'previewDeposit',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'previewMint',
    outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'shares', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'previewRedeem',
    outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'assets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalAssets', type: 'uint256' },
      { internalType: 'uint256', name: 'totalShares', type: 'uint256' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'previewWithdraw',
    outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '', type: 'string' }],
    name: 'registeredCurveNames',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
