export type IconNameType =
  | 'arrow-box-left'
  | 'arrow-left'
  | 'arrow-out-of-box'
  | 'arrow-right'
  | 'arrow-up-right'
  | 'arrows-repeat'
  | 'book'
  | 'bookmark-check'
  | 'brush-sparkle'
  | 'bubble-annotation'
  | 'calendar'
  | 'checkmark'
  | 'chevron-bottom'
  | 'chevron-double-left'
  | 'chevron-double-right'
  | 'chevron-down-small'
  | 'chevron-grabber-vertical'
  | 'chevron-down-large'
  | 'chevron-left'
  | 'chevron-left-small'
  | 'chevron-right'
  | 'chevron-right-small'
  | 'chevron-top-small'
  | 'circle'
  | 'circle-arrow'
  | 'circle-check'
  | 'circle-dots-center'
  | 'circle-plus'
  | 'circle-question-mark'
  | 'circle-x'
  | 'circles-three'
  | 'cross-large'
  | 'crypto-punk'
  | 'crystal-ball'
  | 'dot-grid'
  | 'eye-open'
  | 'eye-slash'
  | 'fast-forward'
  | 'filter-1'
  | 'filter-2'
  | 'floppy-disk-1'
  | 'floppy-disk-2'
  | 'folder'
  | 'graduate-cap'
  | 'group'
  | 'layout-grid'
  | 'layout-third'
  | 'loader'
  | 'lock'
  | 'magnifying-glass'
  | 'medal'
  | 'megaphone'
  | 'microphone'
  | 'moneybag'
  | 'person-circle'
  | 'play'
  | 'play-circle'
  | 'plus-large'
  | 'plus-small'
  | 'rescue-ring'
  | 'rocket'
  | 'settings-gear'
  | 'shield-check'
  | 'shield-check-filled'
  | 'shopping-bag'
  | 'sparkle'
  | 'square-arrow-top-right'
  | 'square-check'
  | 'square-check-empty'
  | 'square-plus'
  | 'square-x'
  | 'trash-can'
  | 'wallet'
  | 'wreath'
  | 'fingerprint'
  | 'x'
  | 'discord'
  | 'lens'
  | 'farcaster'
  | 'calendly'
  | 'medium'
  | 'github'

export const IconName = {
  arrowBoxLeft: 'arrow-box-left',
  arrowLeft: 'arrow-left',
  arrowOutOfBox: 'arrow-out-of-box',
  arrowRight: 'arrow-right',
  ArrowUpRightFromCircleIcon: 'arrow-up-right',
  arrowsRepeat: 'arrows-repeat',
  book: 'book',
  bookmarkCheck: 'bookmark-check',
  brushSparkle: 'brush-sparkle',
  bubbleAnnotation: 'bubble-annotation',
  calendar: 'calendar',
  checkmark: 'checkmark',
  checkmarkBottom: 'checkmark-bottom',
  chevronDoubleLeft: 'chevron-double-left',
  chevronDoubleRight: 'chevron-double-right',
  chevronDownSmall: 'chevron-down-small',
  chevronGrabberVertical: 'chevron-grabber-vertical',
  chevronDownLarge: 'chevron-down-large',
  chevronLeft: 'chevron-left',
  chevronLeftSmall: 'chevron-left-small',
  chevronRight: 'chevron-right',
  chevronRightSmall: 'chevron-right-small',
  chevronTopSmall: 'chevron-top-small',
  circle: 'circle',
  circleArrow: 'circle-arrow',
  circleCheck: 'circle-check',
  circleDotsCenter: 'circle-dots-center',
  circlePlus: 'circle-plus',
  circleQuestionMark: 'circle-question-mark',
  circleX: 'circle-x',
  circlesThree: 'circles-three',
  crossLarge: 'cross-large',
  cryptoPunk: 'crypto-punk',
  crystalBall: 'crystal-ball',
  dotGrid: 'dot-grid',
  eyeOpen: 'eye-open',
  eyeSlash: 'eye-slash',
  fastForward: 'fast-forward',
  filter1: 'filter-1',
  filter2: 'filter-2',
  floppyDisk1: 'floppy-disk-1',
  floppyDisk2: 'floppy-disk-2',
  folder: 'folder',
  graduateCap: 'graduate-cap',
  group: 'group',
  layoutGrid: 'layout-grid',
  layoutThird: 'layout-third',
  loader: 'loader',
  lock: 'lock',
  magnifyingGlass: 'magnifying-glass',
  medal: 'medal',
  megaphone: 'megaphone',
  microphone: 'microphone',
  moneybag: 'moneybag',
  personCircle: 'person-circle',
  play: 'play',
  playCircle: 'play-circle',
  plusLarge: 'plus-large',
  plusSmall: 'plus-small',
  rescueRing: 'rescue-ring',
  rocket: 'rocket',
  settingsGear: 'settings-gear',
  shieldCheck: 'shield-check',
  shieldCheckFilled: 'shield-check-filled',
  shoppingBag: 'shopping-bag',
  sparkle: 'sparkle',
  squareArrowTopRight: 'square-arrow-top-right',
  squareCheck: 'square-check',
  squareCheckEmpty: 'square-check-empty',
  squarePlus: 'square-plus',
  squareX: 'square-x',
  trashCan: 'trash-can',
  wallet: 'wallet',
  wreath: 'wreath',
  fingerprint: 'fingerprint',
  x: 'x',
  discord: 'discord',
  lens: 'lens',
  farcaster: 'farcaster',
  calendly: 'calendly',
  medium: 'medium',
  github: 'github',
}
