export const CLAIM_ACTIONS = {
  SET_CREATED_CLAIM: 'SET_CREATED_CLAIM',
  SET_SELECTED_IDENTITIES: 'SET_SELECTED_IDENTITIES',
  SET_CLAIM_EXISTS: 'SET_CLAIM_EXISTS',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_IDENTITIES: 'SET_IDENTITIES',
  SET_INITIAL_DEPOSIT: 'SET_INITIAL_DEPOSIT',
  SET_SHOW_ERRORS: 'SET_SHOW_ERRORS',
  SET_VALIDATION_ERRORS: 'SET_VALIDATION_ERRORS',
  RESET: 'RESET',
} as const

export type ClaimActionType = (typeof CLAIM_ACTIONS)[keyof typeof CLAIM_ACTIONS]
