services:
  geth:
    image: ethereum/client-go
    ports:
      - '8545:8545'
    entrypoint: sh /root/init-script.sh
    command: '--dev --dev.period=2 --cache=8192 --http --http.api=eth,web3,net --http.port=8545 --http.vhosts=* --http.addr=0.0.0.0 --http.corsdomain="https://remix.ethereum.org" --datadir=/data --password=/root/password.txt'
    volumes:
      - ./data:/data
      - ./geth/genesis.json:/config/genesis.json
      - ./geth/init-script.sh:/root/init-script.sh
      - ./geth/keystore.json:/data/keystore/UTC--2024-06-03T19-15-34.118131000Z--63e87dc2366dc7f1be110ded239879422e165d96
      - ./geth/password.txt:/root/password.txt

  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  firehose:
    depends_on:
      - ipfs
      - geth
    image: ghcr.io/streamingfast/firehose-ethereum:v2.6.0-geth-v1.13.15-fh2.4
    ports:
      - '9000:9000' # Substreams tier 1 gRPC port
    volumes:
      - ./data:/data
    command:
      - start
      - reader-node,merger,relayer,firehose,substreams-tier1,substreams-tier2
      - --data-dir=/data
      - --config-file=
      - --log-format=text
      - --log-to-file=false
      - --common-first-streamable-block=1
      - --reader-node-path=fireeth
      - --reader-node-arguments=tools poller generic-evm http://geth:8545 0 --data-dir=/data
      - --substreams-tier1-grpc-listen-addr=:9000
      - --substreams-state-bundle-size=2
      - --merger-time-between-store-pruning=1s
