name: CI
on:
  pull_request:
    branches:
      - main

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      PINATA_API_JWT: ${{ secrets.PINATA_API_JWT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.11.0

      # Foundry setup for protocol
      - name: Setup foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules/.pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile

      # - name: Set SHAs
      #   uses: nrwl/nx-set-shas@v4

      - name: Run Linting
        run: pnpm lint
      
      # TODO: Figure out why turbo isn't passing from global state.
      - name: Write PINATA_API_JWT to packages/sdk/.env
        run: echo "PINATA_API_JWT=${{ secrets.PINATA_API_JWT }}" >> packages/sdk/.env

      - name: Run Build
        run: pnpm build

      # TODO: Figure out why turbo isn't passing from global state.
      - name: Write MAINNET_RPC_URL to packages/protocol/.env
        run: echo "MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }}" >> packages/protocol/.env

      - name: Run Tests
        run: pnpm test
